---
title: "R Notebook"
---


```{r}
library(data.table)
library(purrr)
library(scDiffCom)
library(ontologyIndex)
library(reshape2)
library(ggplot2)
library(ggpubr)

object = readRDS("../../data_scAgeCom/testing/scDiffCom_test_facs_liver.rds")
GO = get_ontology(file='../../data/go.obo')

BIOLOGICAL_PROCESS_ROOT = 'GO:0008150'
MOLECULAR_FUNCTION_ROOT = 'GO:0003674'
CELLULAR_COMPONENT_ROOT = 'GO:0005575'

BIOLOGICAL_PROCESSES = get_descendants(GO, BIOLOGICAL_PROCESS_ROOT)
MOLECULAR_FUNCTIONS = get_descendants(GO, MOLECULAR_FUNCTION_ROOT)
CELLULAR_COMPONENTS = get_descendants(GO, CELLULAR_COMPONENT_ROOT)
```

```{r}
LR_GO = scDiffCom::LRdb_mouse$LRdb_curated_GO
head(LR_GO)
```

```{r}
LR_GO_BP = LR_GO[GO_ID %in% BIOLOGICAL_PROCESSES]
LR_GO_BP[, 'Indicator' := 1]
LR_GO_BP[, 'GO_NAME' := NULL]
LR_GO_BP_wide = dcast(LR_GO_BP, LR_SORTED ~ GO_ID, value.var = 'Indicator')
LR_GO_BP_wide[is.na(LR_GO_BP_wide)] = 0
rownames(LR_GO_BP_wide) = LR_GO_BP_wide[, "LR_SORTED"]
head(LR_GO_BP_wide)
sum(LR_GO_BP_wide[, 2:3641])
```

```{r}
Num_BPs_per_LR = rowSums(LR_GO_BP_wide[, 2:3641])
Num_LRs_per_BP = colSums(LR_GO_BP_wide[, 2:3641])

hist_from_vector <- function(v, bw=NULL, xlim=NULL, xlab=NULL) {
  return(
    ggplot(data.frame(v), aes(v))
    + geom_histogram(binwidth=bw)
    + coord_cartesian(xlim=xlim)
    + xlab(xlab)
  )
}

g1 = hist_from_vector(Num_BPs_per_LR, bw=5, xlab='Biological processes per LR')
g2 = hist_from_vector(Num_LRs_per_BP, bw=10, xlim=c(0, 500), xlab='Ligand-receptor pairs per biological process')

ggarrange(g1, g2,
          nrow=1, ncol=2)

```

```{r}
dt = LR_GO_BP_wide[, 2:3641]
test = TRUE

compute_similarity_1 <- function(dt, nrows, col1, col2) {
  # binary distance
  return( sum(dt[, col1] == dt[, col2]) / nrows)
}

compute_similarity_2 <- function(dt, nrows, col1, col2) {
  return( sum( (dt[, col1] == dt[, col2]) & (dt[, col1] == 1) ) / sum( (dt[, col1] + dt[, col2]) > 0) )
}

compute_similarity_3 <- function(dt, nrows, col1, col2) {
  
}

binary_distance_matrix <- function(dt, test, similarity_func) {
  
  cols = names(dt)
  if (test) {
    cols = cols[1:100]
  }
  ncols = length(cols)
  nrows = nrow(dt)
  
  mat = matrix(nrow=ncols, ncol=ncols)
  colnames(mat) = cols
  rownames(mat) = cols
  
  
  
  m_ = map(
    1:ncols,
    function(idx1, ...) {
      
      map_dbl(
        idx1:ncols,
        function(idx2, ...) {
          similarity_func(dt, nrows, cols[idx1], cols[idx2])
        },
        idx1,
        dt,
        cols,
        nrows
      )
      
    },
    dt,
    cols,
    nrows
  )
  
  r_ = reduce(m_, c)
  
  counter = 1
  for (i in 1:ncols) {
    for (j in i:ncols) {
      elem_i = cols[i]
      elem_j = cols[j]
      mat[elem_i, elem_j] = r_[counter]
      counter = counter + 1
    }
  }
  
  uppertri_to_complete <- function(uppertri) {
    m = copy(uppertri)
    m[lower.tri(m)] = t(m)[lower.tri(m)]
    return(m)
  }
  
  # mat = mat/nrows  # normalize
  mat = uppertri_to_complete(mat)
  return(mat)
}
```

```{r}
# Compute and save the full distance matrices
# GO_dist = binary_distance_matrix(LR_GO_BP_wide[, 2:3641], test=FALSE)
# saveRDS(GO_dist, 'GO_terms_distance_matrix_similarity1.rds')
# 
# LR_dist = binary_distance_matrix(as.data.frame(t(LR_GO_BP_wide[, 2:3641])), test=FALSE)
# saveRDS(LR_dist, "LR_distance_matrix_similarity1.rds")

# GO_dist = binary_distance_matrix(LR_GO_BP_wide[, 2:3641], test=FALSE, similarity_func=compute_similarity_2)
# saveRDS(GO_dist, 'GO_terms_distance_matrix_similarity2.rds')
# 
# LR_dist = binary_distance_matrix(as.data.frame(t(LR_GO_BP_wide[, 2:3641])), test=FALSE, similarity_func=compute_similarity_2)
# saveRDS(LR_dist, "LR_distance_matrix_similarity2.rds")
```

```{r}
GO_dist = readRDS('../analysis/GO_terms_distance_matrix_similarity1.rds')
GO_sims = GO_dist[upper.tri(GO_dist)]
g3 = hist_from_vector(GO_sims, bw=0.005, xlab='Biological processes similarities - 1')

LR_dist = readRDS('../analysis/LR_distance_matrix_similarity1.rds')
LR_sims = LR_dist[upper.tri(LR_dist)]
g4 = hist_from_vector(LR_sims, bw=0.001, xlab='Ligand-receptors similarities - 1')

GO_dist = readRDS('../analysis/GO_terms_distance_matrix_similarity2.rds')
GO_sims = GO_dist[upper.tri(GO_dist)]
g5 = hist_from_vector(GO_sims, bw=NULL, xlab='Biological processes similarities - 2')

LR_dist = readRDS('../analysis/LR_distance_matrix_similarity2.rds')
LR_sims = LR_dist[upper.tri(LR_dist)]
g6 = hist_from_vector(LR_sims, bw=NULL, xlab='Ligand-receptors similarities - 2')

ggarrange(g3, g4,
          g5, g6,
          nrow=2, ncol=2)
```
```{r}
NUM = 1000
n = dim(GO_dist)[1]
rand_idxs = sample(1:n)[1:NUM]
heatmap(GO_dist[rand_idxs, rand_idxs])
heatmap(LR_dist[rand_idxs, rand_idxs])
```



```{r}
compute_inverse_occurence_frequency_similarity <- function(dt, nrows, col1, col2) {
  v1 = dt[, col1]
  v2 = dt[, col2]
  ncols = ncol(dt)
  
  squared_freq = (rowSums(dt) / ncols)^2
  
  return(sum(map_dbl(
      1:nrows,
      function(i, ...) {
        if (v1[i] == v2[i]) {
          return( 1 / squared_freq[i] )
        }
        else {
          return(0)
        }
      },
      v1, v2, ncols
    )
  ))
}

GO_dist = binary_distance_matrix(LR_GO_BP_wide[, 2:3641], TRUE, compute_inverse_occurence_frequency_similarity)
GO_sims = GO_dist[upper.tri(GO_dist)]
g3 = hist_from_vector(GO_sims, bw=NULL, xlab='Biological processes similarities')
g3

# 
# LR_dist = binary_distance_matrix(as.data.frame(t(LR_GO_BP_wide[, 2:3641])), TRUE, compute_inverse_occurence_frequency_similarity)
# LR_sims = LR_dist[upper.tri(LR_dist)]
# g4 = hist_from_vector(LR_sims, bw=0.001, xlab='Ligand-receptors similarities')
# 
# ggarrange(g3, g4,
#           nrow=1, ncol=2)
```

