default:
    
    #DATA_PATH: "../test_and_comparison/data_results_diffcom_down.rds"
    #RESULTS_DIR: "downstream_test/"
    
    # CUTOFFS
    # detection
    #CUTOFF_SCORE_YOUNG: 0.5
    #CUTOFF_SCORE_OLD: 0.5
    #CUTOFF_CPDB_PVAL_YOUNG: 0.05
    #CUTOFF_CPDB_PVAL_OLD: 0.05
    # significance
    #CUTOFF_PVAL_ADJ: 0.05
    #CUTOFF_LOGFC: 0.5
    
    # COLUMNS' NAMES
    COL_TISSUES: "TISSUE"
    COL_LR_GENES: "LR_GENES"
    COL_L_GENE: "L_GENE"
    COL_R_GENE: "R_GENE"
    COL_LIGAND_CELLTYPE: "L_CELLTYPE"
    COL_RECEPTOR_CELLTYPE: "R_CELLTYPE"
    COL_LIGAND_RECEPTOR_CELLTYPES: "LR_CELLTYPES"
    COL_LR_SCORE_YOUNG: "LR_SCORE_young"
    COL_LR_SCORE_OLD: "LR_SCORE_old"
    COL_LOGFC: "LR_LOGFC"
    COL_LOGFC_ABS: "LR_LOGFC_ABS"
    COL_BH_PVAL: "BH_PVAL_DIFF"
    COL_RAW_PVAL: "PVAL_DIFF"
    COL_LR_DETECTED_YOUNG: "LR_DETECTED_young"
    COL_LR_DETECTED_OLD: "LR_DETECTED_old"
    #COL_LIGAND_EXPRESSION_YOUNG: "Ligand_expr_young"
    #COL_LIGAND_EXPRESSION_OLD: "Ligand_expr_old"
    #COL_LIGAND_DETECTED_YOUNG: "Ligand_detec_rate_young"
    #COL_LIGAND_DETECTED_OLD: "Ligand_detec_rate_old"
    #COL_RECEPTOR_EXPRESSION_YOUNG: "Receptor_expr_young"
    #COL_RECEPTOR_EXPRESSION_OLD: "Receptor_expr_old"
    #COL_RECEPTOR_DETECTED_YOUNG: "Receptor_detec_rate_young"
    #COL_RECEPTOR_DETECTED_OLD: "Receptor_detec_rate_old"
    COL_BH_PVAL_SPECIFICITY_YOUNG: "BH_PVAL_young"
    COL_BH_PVAL_SPECIFICITY_OLD: "BH_PVAL_old"
    